import { NextResponse } from 'next/server';

export async function GET() {
  // Mock group product with grouped addons
  const mockProduct = {
    id: 'test-group-product',
    name: 'Home Cleaning Service Package',
    slug: 'home-cleaning-service-package',
    description: 'Complete home cleaning service with customizable add-ons',
    shortDescription: 'Professional home cleaning with flexible options',
    price: '0.00', // Base price is 0, price comes from addons
    images: ['/assets/img/service/service_1_1.jpg'],
    isFeatured: true,
    categoryId: 'cleaning-services',
    productType: 'group',
    categoryName: 'Cleaning Services',
    categorySlug: 'cleaning-services',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    addons: [
      // Essential Add-ons Group
      {
        id: 'pa1',
        productId: 'test-group-product',
        addonId: 'addon1',
        price: '25.00',
        isRequired: true,
        sortOrder: 1,
        isActive: true,
        addonTitle: 'Basic Room Cleaning',
        addonPrice: '25.00',
        addonDescription: 'Standard cleaning for living rooms, bedrooms',
        addonImage: null,
        addonSortOrder: 1,
        addonGroupId: 'group1',
        groupTitle: 'Essential Add-ons',
        groupDescription: 'Core cleaning services required for every package',
        groupSortOrder: 1,
      },
      {
        id: 'pa2',
        productId: 'test-group-product',
        addonId: 'addon2',
        price: '35.00',
        isRequired: true,
        sortOrder: 2,
        isActive: true,
        addonTitle: 'Kitchen Deep Clean',
        addonPrice: '35.00',
        addonDescription: 'Complete kitchen cleaning including appliances',
        addonImage: null,
        addonSortOrder: 2,
        addonGroupId: 'group1',
        groupTitle: 'Essential Add-ons',
        groupDescription: 'Core cleaning services required for every package',
        groupSortOrder: 1,
      },
      {
        id: 'pa3',
        productId: 'test-group-product',
        addonId: 'addon3',
        price: '30.00',
        isRequired: true,
        sortOrder: 3,
        isActive: true,
        addonTitle: 'Bathroom Sanitization',
        addonPrice: '30.00',
        addonDescription: 'Deep bathroom cleaning and sanitization',
        addonImage: null,
        addonSortOrder: 3,
        addonGroupId: 'group1',
        groupTitle: 'Essential Add-ons',
        groupDescription: 'Core cleaning services required for every package',
        groupSortOrder: 1,
      },
      // Premium Options Group
      {
        id: 'pa4',
        productId: 'test-group-product',
        addonId: 'addon4',
        price: '45.00',
        isRequired: false,
        sortOrder: 4,
        isActive: true,
        addonTitle: 'Carpet Steam Cleaning',
        addonPrice: '45.00',
        addonDescription: 'Professional carpet steam cleaning service',
        addonImage: null,
        addonSortOrder: 1,
        addonGroupId: 'group2',
        groupTitle: 'Premium Options',
        groupDescription: 'Enhanced cleaning services for a premium experience',
        groupSortOrder: 2,
      },
      {
        id: 'pa5',
        productId: 'test-group-product',
        addonId: 'addon5',
        price: '40.00',
        isRequired: false,
        sortOrder: 5,
        isActive: true,
        addonTitle: 'Window Cleaning (Interior)',
        addonPrice: '40.00',
        addonDescription: 'Interior window cleaning for all rooms',
        addonImage: null,
        addonSortOrder: 2,
        addonGroupId: 'group2',
        groupTitle: 'Premium Options',
        groupDescription: 'Enhanced cleaning services for a premium experience',
        groupSortOrder: 2,
      },
      // Specialty Services Group
      {
        id: 'pa6',
        productId: 'test-group-product',
        addonId: 'addon6',
        price: '60.00',
        isRequired: false,
        sortOrder: 6,
        isActive: true,
        addonTitle: 'Oven Deep Clean',
        addonPrice: '60.00',
        addonDescription: 'Complete oven interior and exterior cleaning',
        addonImage: null,
        addonSortOrder: 1,
        addonGroupId: 'group3',
        groupTitle: 'Specialty Services',
        groupDescription: 'Specialized cleaning for specific appliances and areas',
        groupSortOrder: 3,
      },
      {
        id: 'pa7',
        productId: 'test-group-product',
        addonId: 'addon7',
        price: '50.00',
        isRequired: false,
        sortOrder: 7,
        isActive: true,
        addonTitle: 'Refrigerator Cleaning',
        addonPrice: '50.00',
        addonDescription: 'Interior and exterior refrigerator deep clean',
        addonImage: null,
        addonSortOrder: 2,
        addonGroupId: 'group3',
        groupTitle: 'Specialty Services',
        groupDescription: 'Specialized cleaning for specific appliances and areas',
        groupSortOrder: 3,
      },
      // Ungrouped addon
      {
        id: 'pa8',
        productId: 'test-group-product',
        addonId: 'addon8',
        price: '20.00',
        isRequired: false,
        sortOrder: 8,
        isActive: true,
        addonTitle: 'Extra Supplies',
        addonPrice: '20.00',
        addonDescription: 'Additional cleaning supplies and materials',
        addonImage: null,
        addonSortOrder: 1,
        addonGroupId: null,
        groupTitle: null,
        groupDescription: null,
        groupSortOrder: null,
      },
    ]
  };

  return NextResponse.json(mockProduct);
} 